#!/bin/bash

This_Dir="`dirname \"$0\"`"

export MCsquare_Materials_Dir=$This_Dir/Materials

if [ "$(uname)" == "Darwin" ]; then 
	export DYLD_LIBRARY_PATH=$This_Dir/lib_mac:$DYLD_LIBRARY_PATH
	if sysctl -a | grep --quiet AVX
  		then $This_Dir/MCsquare_mac
  		else $This_Dir/MCsquare_mac_NoArch
	fi
else
	if cat /proc/cpuinfo | grep --quiet avx512
  		then $This_Dir/MCsquare_linux_avx512
	elif cat /proc/cpuinfo | grep --quiet avx2
		then $This_Dir/MCsquare_linux_avx2
	elif cat /proc/cpuinfo | grep --quiet avx
		then $This_Dir/MCsquare_linux_avx
	elif cat /proc/cpuinfo | grep --quiet sse4
		then $This_Dir/MCsquare_linux_sse4
  	else $This_Dir/MCsquare_linux
	fi
fi
