name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3bbdaf75-6728-492e-a18c-be654dae9ee2/intel-oneapi-hpc-toolkit-2025.2.0.576_offline.exe
  WINDOWS_INTEL_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common:intel.oneapi.win.mkl.devel

jobs:
  linux-gcc-nomkl:
    name: ubuntu-gcc-nomkl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Configure (Release)
        run: |
          cmake -S . -B build \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Package
        run: cpack -C Release -G TGZ --config ./build/CPackConfig.cmake

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ runner.arch }}
          path: "*.tar.gz"
          retention-days: 7

  macos-gcc-nomkl:
    strategy:
      matrix:
        osver: [13,latest]
    name: macos-gcc-nomkl-${{ matrix.osver }}
    runs-on: macos-${{ matrix.osver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          brew update
          brew install cmake libomp gcc@12

      - name: Configure (Release)
        run: |
          cmake -S . -B build \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc-12 \
            -DCMAKE_CXX_COMPILER=g++-12

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Package
        run: cpack -C Release -G TGZ --config ./build/CPackConfig.cmake

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ runner.arch }}
          path: "*.tar.gz"
          retention-days: 7

  windows-msvc-nomkl:
    name: windows-msvc-nomkl
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (Release, x64)
        run: |
          cmake -S . -B build ^
            -G "Visual Studio 17 2022" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -A x64
        shell: cmd

      - name: Build
        run: cmake --build build --config Release -- /m
        shell: cmd

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
        shell: bash

      - name: Package
        run: cpack -C Release -G ZIP --config .\build\CPackConfig.cmake

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ runner.arch }}
          path: "*.zip"
          retention-days: 7

  windows-intel-mkl:
    name: windows-intel-mkl
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Intel Compiler Installation Cache
        uses: actions/cache@v4
        id: cache-install
        with:
          path: |
            C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat
            C:\Program Files (x86)\Intel\oneAPI\compiler
          key: install-${{ runner.os }}-${{ env.WINDOWS_HPCKIT_URL }}-${{ env.WINDOWS_INTEL_COMPONENTS }}

      - name: Install Intel Compiler
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          curl.exe --output %TEMP%\intel-installer.exe --url %WINDOWS_HPCKIT_URL%
          %TEMP%\intel-installer.exe -s -x -f intel-installer-dir --log output.log
          intel-installer-dir\bootstrapper.exe -s --action install --components=%WINDOWS_INTEL_COMPONENTS% --eula=accept -p=NEED_VS2017_INTEGRATION=0 -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=1 --log-dir=.
        shell: cmd

      - name: Configure (Release, x64)
        run: |
          call "C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat" vs2022 && cmake -S . -B build ^
            -G "Visual Studio 17 2022" ^
            -A x64 ^
            -T "Intel C++ Compiler 2025" ^
            -DUSE_MKL_LIB=ON
        shell: cmd

      - name: Build
        run: cmake --build build --config Release -- /m
        shell: cmd

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
        shell: bash

      - name: Package
        run: cpack -C Release -G ZIP --config .\build\CPackConfig.cmake

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}-${{ runner.arch }}
          path: "*.zip"
          retention-days: 7
